### ISSUE TITLE
Backtests for Intraday Strategies which involve exiting trade at particular time before auto square off

### ISSUE THREAD

**Issue by rahulmr** [kieran-mackle/AutoTrader#15]
**Is your feature request related to a problem? Please describe.**
Not sure whether it is request but would like to know how we can perform backtests for intraday strategies.
Time frame 5 min something like that. Yfinance gives data for intraday only for 2 months (1 min or 5 min data).

**Describe the solution you'd like**
Facility to run intraday backtests using say 5 min timeframe data. Solution is to have local csv files and call them in pandas and use for analysis.

**Describe alternatives you've considered**
Download csv data and run backtest using that data

**Additional context**
Brokers provide 5 min data for 60 days only if we want more data we need to run in loop for every 2 months.
And only 5 years data is available for zerodha like Indian broker

**Comment by kieran-mackle** [comment]
This can be achieved using the `data_file` attribute of an AutoTrader instance. See the [Getting Price Data](https://kieran-mackle.github.io/AutoTrader/tutorials/price-data#providing-your-own-data) docs for an example. As a quick summary, you can provide the file name of your data as follows:

```py
from autotrader.autotrader import AutoTrader

at = AutoTrader()
at.data_file = 'price_data.csv'
```

Just make sure that your file, eg. `price_data.csv`, is in a `price_data` sub-directory of your project, as this is where AutoTrader will search for it.

**Comment by kieran-mackle** [comment]
@rahulmr I have just added a new method, `add_data` to AutoTrader ([`v0.5.21`](https://pypi.org/project/autotrader/)), which adds a bit more capability to providing local data files. See the documentation for this method [here](https://kieran-mackle.github.io/AutoTrader/docs/autotrader#providing-local-data).
