### ISSUE TITLE
Futures-coin support for binance

### ISSUE THREAD

**Issue by nitlott** [kieran-mackle/AutoTrader#19]
**Describe the solution you'd like**
Futures-coin support for binance to trade things like bnbperp or others would be awesome.

**Comment by kieran-mackle** [comment]
@nitlott 

This is now possible through the integration of [CCXT](https://github.com/ccxt/ccxt) in AutoTrader version 0.7.

Make sure to read the [docs](https://autotrader.readthedocs.io/en/latest/index.html) and [changelog](https://autotrader.readthedocs.io/en/latest/changelog.html) if upgrading, as there have been a lot of changes!
