### ISSUE TITLE
building-strategy.md is missing PERIOD: 300

### ISSUE THREAD

**Issue by rez1-inf** [kieran-mackle/AutoTrader#27]
**Describe the bug**
`building-strategy.md` in `/docs/source/tutorials/` is missing `PERIOD: 300` which causes a `KeyError` when running a test<br>If someone just follows the tutorial without using the demo repo, then it becomes an issue.<br>Although, this maybe a very minor issue. I just stumbled on it and thought of letting you guys know.

**To Reproduce**
1. Go to '[building-strategy.md](https://github.com/kieran-mackle/AutoTrader/blob/main/docs/source/tutorials/building-strategy.md)'
2. Scroll down to '[Strategy Configuration](https://github.com/kieran-mackle/AutoTrader/blob/main/docs/source/tutorials/building-strategy.md#strategy-configuration)'
3. Scroll down a little more until you see the code block example for a `strategy.yaml`

**Expected behavior**
Expected `PERIOD: 300` key/value within the example but is missing. But the demo repository has `PERIOD: 300` in it's .yaml file

**Screenshots**
![ScreenShot](https://user-images.githubusercontent.com/19827480/162670891-24e19c8d-a567-456a-a463-eec9f49450b5.png)

**Version of AutoTrader being used**
N/A (master repository)

**Additional context**
It is also in '[ReadTheDocs.io](https://py-autotrader.readthedocs.io/en/latest/tutorials/building-strategy.html)

**Comment by kieran-mackle** [comment]
Thank you for pointing this out! Not sure how I didn't copy that specifically when writing the docs. I've updated the docs accordingly.
