### ISSUE TITLE
autodetect_divergence can not be plot 

### ISSUE THREAD

**Issue by kitkimwong** [kieran-mackle/AutoTrader#32]
**Describe the bug**
ValueError: You are trying to merge on datetime64[ns, UTC] and int64 columns. If you wish to proceed you should use pd.concat

**To Reproduce**

> from finta import TA
> from autotrader.autodata import GetData
> from autotrader.autoplot import AutoPlot
> from autotrader.indicators import crossover, cross_values
> from autotrader import indicators
> 
> get_data = GetData()
> 
> instrument = 'EURUSD=X'
> data = get_data.yahoo(instrument, '1d', 
>                       start_time='2021-01-01', 
>                       end_time='2021-04-01')
> ema50 = TA.EMA(data, 50)
> rsi =TA.RSI(data,12)
> 
> rsi_divergence = indicators.autodetect_divergence(data, rsi)
> 
> indicator_dict = {
>     'EMA (50)': {'type': 'MA',
>                           'data': ema50},
>     'RSI (14)': {'type': 'RSI',
>                                'data': rsi},
>                   'Bullish divergence': {'type': 'below',
>                                          'data': rsi_divergence['regularBull']},
>                   }
> 
> ap = AutoPlot(data)
> ap.plot(indicators=indicator_dict, instrument=instrument)
> 

**Screenshots**
![image](https://user-images.githubusercontent.com/11818108/167087759-7cab2cf9-2eab-4713-923d-a3bd5ba548ce.png)

**Version of AutoTrader being used**
master

**Comment by kitkimwong** [comment]
@kieran-mackle

**Comment by kieran-mackle** [comment]
Fixed this in [504d6df](https://github.com/kieran-mackle/AutoTrader/commit/504d6df3e4fea2e315175e249efeabb311ff3fe9).
