### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by lleewwiiss** [kieran-mackle/AutoTrader#34]
**Describe the bug**
Read the Docs link are currently down for the documentation.

**To Reproduce**
1. Go to https://py-autotrader.readthedocs.io/en/latest/

**Expected behavior**
Read the docs :P

**Screenshots**
![image](https://user-images.githubusercontent.com/7379418/168191123-6b0042a2-529d-42d1-9142-497c4c0445c1.png)

**Version of AutoTrader being used**
n/a

**Additional context**
n/a

**Comment by kieran-mackle** [comment]
Sorry about that, I have just changed the domain name. The docs can now be found at: https://autotrader.readthedocs.io/en/latest/

I'll update the links throughout the repo now.
