### ISSUE TITLE
Need to update emailing.py related import. 

### ISSUE THREAD

**Issue by ChiahungTai** [kieran-mackle/AutoTrader#46]
**Describe the bug**
The emailing.py is moved to autotraders.comms, the  code `from autotrader.emailing import send_order_summary` might not be working in autotrader.bin.email_manager.py

**To Reproduce**
1. run autotrader.bin.email_manager.py directly.

**Expected behavior**
Should not show error/

**Screenshots**
ModuleNotFoundError: No module named 'autotrader.emailing'

**Version of AutoTrader being used**
0.7.2

**Additional context**

**Comment by kieran-mackle** [comment]
fixed in https://github.com/kieran-mackle/AutoTrader/commit/de66b39569006146f23f9c8cd20b860bc232ab6d
