### ISSUE TITLE
New broker templete

### ISSUE THREAD

**Issue by bibinvargheset** [kieran-mackle/AutoTrader#47]
I saw thw new broker templete, but it is missing key information , 

1. There should what is expected return format for each methods
2. it does not includes the data loaded info since each broker may have different data methods and different instruments, there should be a possibility of addinfg that

**Comment by kieran-mackle** [comment]
Hi @bibinvargheset,

I have added an abstract class `autotrader.brokers.broker.AbstractBroker` (#60) which provides an interface for all broker modules. I have also updated the template file accordingly.
