### ISSUE TITLE
dydx Connectivity

### ISSUE THREAD

**Issue by jfitz001** [kieran-mackle/AutoTrader#52]
Hi there,
I am looking to live trade with dydx, but when I am attempting to connect and run a basic algorithm, I am getting errors.

The first one is: AutoData is not defined. I fixed this by importing the class in the dydx/broker.py file.

The next one is related to the data feed. The system exits right after the prompt "Please specify a data feed" shows up.

Any help would be greatly appreciated!
Jamie
![Capture](https://user-images.githubusercontent.com/52320660/191876137-3546fd08-ed02-46cc-8c7b-24002a3d89aa.PNG)

**Comment by jfitz001** [comment]
![Uploading Capture.PNG…]()

**Comment by jfitz001** [comment]
![Capture](https://user-images.githubusercontent.com/52320660/191877000-76c5f372-8e77-4646-8738-74b2204f9cf2.PNG)

**Comment by kieran-mackle** [comment]
Hi Jamie,

Thanks for raising this, I've fixed the `AutoData` import bug. You can upgrade by either re-pulling the repo or `pip install --upgrade autotrader`.

As per your other question, you need to tell AutoTrader where to find data to provide your strategy. If you have not set anything custom up for this, I imagine you would just like to pull price data directly from dYdX. In this case, you must specify `feed="dydx"` in `AutoTrader.configure`. This will create an instance of `AutoData` which connects to dYdX's public data API and pulls the latest price data each time your strategy is called for new trading signals.

I have tested your run file above locally and everything seems to be running fine, but please let me know if you still have issues. On another note, if you are using the example `macd` strategy, please note that it was written with `periodic` update mode, not `continuous` mode as in your example (which is now default - no need to specify it).

Let me know if you have any more questions!

**Comment by jfitz001** [comment]
Hi Kieran,
Thanks for the quick response! Really like this package you built so I appreciate the help. Looks like it's working for me too, so thanks again.

**Comment by jfitz001** [comment]
One follow up question...have you tested the dydx functionality live? 

My code for the example macd is different, where I am just entering a trade if its greater/less than a 2 period moving average. I was lazy and didn't change the name of it.

I've been letting it run for a while and no trades are showing up. 

Appreciate the help,
Jamie

**Comment by kieran-mackle** [comment]
Yes, though I was running a different sort of strategy. from your run script, you have it set to update once per day. Maybe that is a typo? I wouldn't expect you to see many trades on that frequency, depending on the size of your watchlist.

**Comment by jfitz001** [comment]
Thanks for sending an example as well. I modified it to be at the 1 minute level. 

Any advice in dealing with this decimal error?
![image](https://user-images.githubusercontent.com/52320660/191886309-17a92ad0-24e5-4bf1-af5d-49ad80ad8590.png)

**Comment by kieran-mackle** [comment]
@jfitz001 

Sorry about that - another bug on my end. All fixed now though, if you update again to `v0.7.7` it should hopefully work as expected.

Let me know!

**Comment by jfitz001** [comment]
I think the reason it wasn't working for me is because the size was not specified. Is there a way to do a proportion of the total account balance in the order function you sent earlier?

**Comment by jfitz001** [comment]
@kieran-mackle Also noticed when i deployed the live trader that the trade keeps executing. Is there a method to check if there is an open position prior to trading?

**Comment by kieran-mackle** [comment]
@jfitz001 

You can query your current account balance/NAV to calculate trade sizes. For example, something like:
```
nav = broker.get_NAV()
size = fraction * nav / last_price
```


As per your second question, that would be expected behaviour, if for example price stays above the 2 period moving average each update. If you only want to enter when this condition is first met, you can either create a signal from the crossover event (you might find [this indicator](https://autotrader.readthedocs.io/en/latest/indicators.html#crossover) useful), or you can also check your current position, as you suggested. To do the latter, use something like:
```
position = broker.get_positions(instrument)
```
The returned object will be a dictionary of the form `{instrument: Position}`, where `instrument` is a string, and `Position` is a [`Position`](https://autotrader.readthedocs.io/en/latest/broker/trading.html#positions) object. You can then check for a position using `len(position) > 0`, if there is no open position, an empty dict `{}` will be returned. 

I admit the docs are a bit lacking here, so I recommend trying these commands manually to get a feel for them before deploying them in the strategy. For example:
```
from autotrader import AutoTrader, Order

at = AutoTrader()
at.configure(broker="dydx")
broker = at.run()

# Get all positions
positions = broker.get_positions()

# Get position in single instrument
ETH_pos = broker.get_positions("ETH-USD")
```

Hope that helps.

**Comment by jfitz001** [comment]
Yes that was very helpful. The next step is figuring out how to use the NAV/position sizing capabilities within the .add_strategy.

Something like this: 
![image](https://user-images.githubusercontent.com/52320660/192123759-7207bc6e-5a3a-4d39-b06f-b9e2f3c27d61.png)

**Comment by kieran-mackle** [comment]
I recommend having a look over the docs, particularly how to gain [broker access from your strategy](https://autotrader.readthedocs.io/en/latest/userfiles/strategy.html?highlight=include%20broker#broker-access) and the [strategy configuration](https://autotrader.readthedocs.io/en/latest/userfiles/strategy-configuration.html#configuration-options). Hopefully that will make things clear, but the code below is a good starter. Note that you can simply append any orders created to the `orders` list.

```python
def __init__(self, instrument, broker, **kwargs):
    self.instrument = instrument
    self.broker = broker

def generate_signal(self, data):
    orders = []
    self.generate_features(data)
    
    # Fetch current position in self.instrument
    current_position = self.broker.get_positions(self.instrument)

    if not current_position:
        # Not position held

        # Check entry strategy logic
    
    else:
        # A position is held

        # Check exit logic
    
    return orders
```
