### ISSUE TITLE
unexpected keyword argument 'strategy_filename'

### ISSUE THREAD

**Issue by mikmolefe** [kieran-mackle/AutoTrader#64]
Hi,
Running demo run_scan.py for autotrader-0.9.1 returns the following error for macd strattegy:

raceback (most recent call last):
File "run_scan.py", line 12, in
at.run()
File "/home/kgori/.local/lib/python3.8/site-packages/autotrader/autotrader.py", line 933, in run
self.add_strategy(strategy_filename=strat_config_file)
TypeError: add_strategy() got an unexpected keyword argument 'strategy_filename'

Thanks

**Comment by kieran-mackle** [comment]
Hi @mikmolefe,

I've just updated the example file and tested it - should all be working now.
