### ISSUE TITLE
plotting error

### ISSUE THREAD

**Issue by alihaskar** [kieran-mackle/AutoTrader#68]
i tried running the demo as is,it runs perfectly until it reaches plotting where it raises 

> AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width. 

i guess this has to do with the old version of bokeh Autotrader is using

**Comment by alihaskar** [comment]
it worked when i downgraded bokeh to bokeh-2.3.2

**Comment by kieran-mackle** [comment]
Thanks @alihaskar, I will make sure to fix the Bokeh dependency or update the code for this. Thanks for letting me know.

**Comment by noubre** [comment]
@kieran-mackle I am running into this same error even though bokeh is already version 2.3.2. Could there be another reason for the error that I am missing?

Thanks!
