### ISSUE TITLE
Interactive Brokers

### ISSUE THREAD

**Issue by Polypod** [kieran-mackle/AutoTrader#8]
Noted that support for IB was planned, but did not spot any draft implementation

Was thinking of implementing Interactive-Brokers support through using IB-Insync framework for simplicity(mainly using it for stocks), but if you already have something cooking that would save time and effort of course..
https://github.com/erdewit/ib_insync.git

Note that I'm still on a steep learning curve, so things go slow ; )
Thanks for a nice package anyway.

**Comment by kieran-mackle** [comment]
That would be very welcomed! I do not have any work-in-progress for IB, so unfortunately you would be starting from scratch. However, using the virtual broker module as a template for the methods required is a good starting point. 

Feel free to start by adding just the methods you require for your own trading, and I can fill in the gaps for the other methods.

**Comment by Polypod** [comment]
Had a first go at adapting based on Oanda.py to IB in /brokers/... Not sure if on the right track, let me know :). Far from finished in any case..
Fork here:
https://github.com/Polypod/AutoTrader.git

**Comment by kieran-mackle** [comment]
That looks good so far. The only 'rule' you will need to follow is to make sure that each method in the virtual broker (as a reference point) is replicated in `interactive_borkers.py`. The outputs of each method should also be consistent in type a dimensionality, or as similar as possible. This is to ensure that the same strategies can easily be run with either broker. It looks like you might have noted this already though. Everything looks good!

I am on holiday right now but I will aim to integrate the support structure for your IB broker module throughout the rest of the code, so that you can do testing through AutoTrader. In the meantime, running some unit tests on the methods you develop should be enough to debug.

Thank you for your efforts!

**Comment by kieran-mackle** [comment]
I have added a few blocks of code which should make integration of your work a bit easier. The first is in the [environment manager](https://github.com/kieran-mackle/AutoTrader/blob/main/autotrader/lib/environment_manager.py), which is responsible for constructing the broker configuration dictionary from the global configuration file. I have only added a placeholder, as I am not familiar with IB and what information will be required. However, you simply need to add the appropriate information to the `config_dict` on lines 35 and 65, for live trading and demo trading, respectively. You can use the Oanda `config_dict` as a guiding example.

The second addition I have made is the import of the IB broker modules you are working on in the [autotrader](https://github.com/kieran-mackle/AutoTrader/blob/main/autotrader/autotrader.py) module. Specifically, see [lines 857 to 861](https://github.com/kieran-mackle/AutoTrader/blob/main/autotrader/autotrader.py#L857-L861) of the `_assign_broker` method. This creates an instance of the `ib_broker` module and assigns it to AutoTrader as the broker API. Note that I have commented out the `import` statement on line 26 to prevent any errors, as the main codebase does not have your modules in it yet. 

Note that I have defined all of the IB specific features to be activated when using the `feed` of `IB`. 

Let me know how you are going, and feel free to send me any questions over email: [kemackle98@gmail.com](mailto:kemackle98@gmail.com).

**Comment by kieran-mackle** [comment]
@Polypod AutoTrader `v0.6.0` now includes a broker module for Interactive Bokers. Quite a few things have changed in this release, so make sure to check the docs if you update!

**Comment by Polypod** [comment]
Hi Kieran,That’s really good news!Apologies for not contributing to this – I have just had too little time to explore how to add that broker (besides my limit in coding experience).For the historical data from IBKR, I suggest maybe to use something like this: def _get_historical_data(self, instrument: str, bar: str = None,                         end_date: str = '', use_RTH=True):    """Returns historical price data.    """    self._check_connection()    # self.ib.reqHistoricalData()    # raise NotImplementedError("This method is not available.")    """           Get historical bars for instrument.           https://interactivebrokers.github.io/tws-api/historical_bars.html           """    # Get max duration for a given bar size    if bar in ['1 day', '1 week', '1 month']:        duration = '1 Y'  # one year    elif bar in ['30 mins', '1 hour', '2 hours', '3 hours', '4 hours', '8 hours']:        duration = '1 M'  # one month    elif bar in ['3 mins', '5 mins', '10 mins', '15 mins', '20 mins']:        duration = '1 W'  # one week    elif bar == '2 mins':        duration = '2 D'  # two days    elif bar == '1 min':        duration = '1 D'  # one day    else:        raise ValueError(            'Invalid bar: {} for get_historical_data()'.format(bar))    # Get historical bars    bars = self.ib.reqHistoricalData(        instrument,        endDateTime=end_date,        durationStr=duration,        barSizeSetting=bar,        whatToShow='TRADES',        useRTH=use_RTH)  # use regular trading hours    # Convert bars to a pandas dataframe    hist = util.df(bars)    # Make the 'date' column the index    hist.set_index('date', inplace=True)    # Remove the 'barCount', and 'average' columns    # hist.drop(columns=['volume', 'barCount', 'average'], inplace=True)    hist.drop(columns=['barCount', 'average'], inplace=True)    hist.index = hist.index.tz_localize(timezone.utc)    return hist Cheers,H Sent from Mail for Windows From: Kieran MackleSent: Thursday, March 31, 2022 6:12 AMTo: kieran-mackle/AutoTraderCc: Henrik E; MentionSubject: Re: [kieran-mackle/AutoTrader] Interactive Brokers (Issue ***@***.*** AutoTrader v0.6.0 now includes a broker module for Interactive Bokers. Quite a few things have changed in this release, so make sure to check the docs if you update!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Polypod** [comment]
Thanks, good news! My apologies for not contributing much, have been swamped w work.
Will start testing the IB broker a bit.
For historical data (seems the first hurdle), maybe something like the below would work (did not look into Utils.build_contract(order) right now):

def _get_historical_data(self, instrument: str, order: Order, bar: str = None,
                             end_date: str = '', use_RTH=True):
        """Returns historical price data.
        """
        self._check_connection()
        # self.ib.reqHistoricalData()
        # raise NotImplementedError("This method is not available.")

        contract = Utils.build_contract(order)
        self.ib.qualifyContracts(contract)

        """
               Get historical bars for instrument.
               https://interactivebrokers.github.io/tws-api/historical_bars.html
               """
        # Get max duration for a given bar size
        if bar in ['1 day', '1 week', '1 month']:
            duration = '1 Y'  # one year
        elif bar in ['30 mins', '1 hour', '2 hours', '3 hours', '4 hours', '8 hours']:
            duration = '1 M'  # one month
        elif bar in ['3 mins', '5 mins', '10 mins', '15 mins', '20 mins']:
            duration = '1 W'  # one week
        elif bar == '2 mins':
            duration = '2 D'  # two days
        elif bar == '1 min':
            duration = '1 D'  # one day
        else:
            raise ValueError(
                'Invalid bar: {} for get_historical_data()'.format(bar))

        # Get historical bars
        bars = self.ib.reqHistoricalData(
            contract,
            endDateTime=end_date,
            durationStr=duration,
            barSizeSetting=bar,
            whatToShow='TRADES',
            useRTH=use_RTH)  # use regular trading hours

        # Convert bars to a pandas dataframe
        hist = util.df(bars)

        # Make the 'date' column the index
        hist.set_index('date', inplace=True)

        # Remove the 'barCount', and 'average' columns (need to rename, e.g. close → Close?)
        hist.drop(columns=['barCount', 'average'], inplace=True)

        hist.index = hist.index.tz_localize(timezone.utc)

        return hist
