### ISSUE TITLE
The requested range must be within the last 730 days, 'Index' object has no attribute 'tzinfo', and so on ~

### ISSUE THREAD

**Issue by ahmadekoekkoek** [kieran-mackle/AutoTrader#81]
I encountered numerous issues while attempting to run the main **runfile.py**
Based on the error messages, it seems that the problems lie within the module, which results in the failure to execute when calling the methods **at.run()**.
I would greatly appreciate your guidance in resolving these issues.
Thank you.

![RunfileERROR](https://user-images.githubusercontent.com/122379976/231851469-2f1e6c37-f2bb-4c49-80d4-751f867fede9.png)

**Comment by byteboon** [comment]
So make your date range within the last 730 days...

`at.backtest(start = '1/1/2022', end = '1/5/2023')`
