### ISSUE TITLE
Integrate existing indicator library

### ISSUE THREAD

**Issue by yokotsumo** [kieran-mackle/AutoTrader#89]
**Is your feature request related to a problem? Please describe.**
I would like to integrate existing TA indicator libraries (pandas_ta, TA Lib, custom .py files) and use them seamlessly with the current Autotrader instructions

**Describe the solution you'd like**
I would like to know the proper way to do it

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kieran-mackle** [comment]
You can use these libraries from within your strategy - this is already illustrated in many of the examples. For example, the [macd strategy](https://github.com/kieran-mackle/autotrader-demo/blob/main/strategies/macd.py#L1) uses the [finta](https://github.com/peerchemist/finta) library. Simply import the desired function from your strategy and apply it to the data.

**Comment by yokotsumo** [comment]
Thank you for the quick answer.
