### ISSUE TITLE
Help beginners run the project locally

### ISSUE THREAD

**Issue by owinoalfred** [kieran-mackle/AutoTrader#91]
I have tried for days to run this thing tried everything, which part of the docs explains installation and commands to run locally.

**Comment by kieran-mackle** [comment]
Hi - what exactly are you having trouble with? 

Could you please tell me what you have tried and what the error messages are?

Installation instructions are on the [README of this repo](https://github.com/kieran-mackle/AutoTrader#installation), as well as on the [documentation site](https://autotrader.readthedocs.io/en/latest/), linked multiple times throughout this repo and on the sidebar.

There is also an [entire repo with example strategies](https://github.com/kieran-mackle/autotrader-demo), also linked on the [README](https://github.com/kieran-mackle/AutoTrader#documentation) and on the docs site.

If are not sure how to run AutoTrader, there is both a [condensed tutorial](https://autotrader.readthedocs.io/en/latest/tutorials/condensed-walkthrough.html) and [a very detailed walkthrough](https://autotrader.readthedocs.io/en/latest/tutorials/walkthrough.html) on the docs site.

If you need any more information, let me know.

**Comment by owinoalfred** [comment]
(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>python runfile.py  

░█████╗░██╗░░░██╗████████╗░█████╗░████████╗██████╗░░█████╗░██████╗░███████╗██████╗░
██╔══██╗██║░░░██║╚══██╔══╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
███████║██║░░░██║░░░██║░░░██║░░██║░░░██║░░░██████╔╝███████║██║░░██║█████╗░░██████╔╝
██╔══██║██║░░░██║░░░██║░░░██║░░██║░░░██║░░░██╔══██╗██╔══██║██║░░██║██╔══╝░░██╔══██╗
██║░░██║╚██████╔╝░░░██║░░░╚█████╔╝░░░██║░░░██║░░██║██║░░██║██████╔╝███████╗██║░░██║
╚═╝░░╚═╝░╚═════╝░░░░╚═╝░░░░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['AUDJPY=X']: Exception('%ticker%: 1h data not available for startTime=1609459200 and endTime=1651363200. The requested range must be within the last 730 days.')
Traceback (most recent call last):
  File "C:\dev\autotrader-demo-main\autotrader-demo-main\runfile.py", line 9, in <module>
    at.run()
  File "C:\dev\AutoTrader-main\autotrader\autotrader.py", line 1142, in run
    self._main()
  File "C:\dev\AutoTrader-main\autotrader\autotrader.py", line 1613, in _main
    bot = AutoTraderBot(
  File "C:\dev\AutoTrader-main\autotrader\autobot.py", line 223, in __init__
    self._refresh_data(deploy_dt)
  File "C:\dev\AutoTrader-main\autotrader\autobot.py", line 449, in _refresh_data
    data, multi_data, quote_data, auxdata = self.Stream.refresh(timestamp=timestamp)
  File "C:\dev\AutoTrader-main\autotrader\utilities.py", line 1174, in refresh
    data = data_func(
  File "C:\dev\AutoTrader-main\autotrader\autodata.py", line 783, in _yahoo
    if data.index.tzinfo is None:
AttributeError: 'Index' object has no attribute 'tzinfo'

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>


**also this pops up when i run the demo**

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>autotrader demo  
Loading demo files...
  Done.
Traceback (most recent call last):
  File "C:\dev\autotrader-demo-main\autotrader-demo-main\macd_strategy.py", line 3, in <module>
    from finta import TA
ModuleNotFoundError: No module named 'finta'

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>pip install finta
Requirement already satisfied: finta in c:\dev\autotrader-main\venv\lib\site-packages (1.3)
Requirement already satisfied: numpy in c:\dev\autotrader-main\venv\lib\site-packages (from finta) (1.26.1)
Requirement already satisfied: pandas in c:\dev\autotrader-main\venv\lib\site-packages (from finta) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2023.3)
Requirement already satisfied: six>=1.5 in c:\dev\autotrader-main\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->finta) (1.16.0)

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>

**Comment by kieran-mackle** [comment]
As it says in the message above, 1h data is not available for date range requested, from `yfinance`. You must update this date range to something more recent, or provide your own data.

The other message also says that you are missing the `finta` package. You can install this as usual:
```
pip install finta
```

**Comment by owinoalfred** [comment]
I did that already, 

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>autotrader demo
Loading demo files...
  Done.
Traceback (most recent call last):
  File "C:\dev\autotrader-demo-main\autotrader-demo-main\macd_strategy.py", line 3, in <module>
    from finta import TA
ModuleNotFoundError: No module named 'finta'

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>pip install finta
Requirement already satisfied: finta in c:\dev\autotrader-main\venv\lib\site-packages (1.3)
Requirement already satisfied: numpy in c:\dev\autotrader-main\venv\lib\site-packages (from finta) (1.26.1)
Requirement already satisfied: pandas in c:\dev\autotrader-main\venv\lib\site-packages (from finta) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\dev\autotrader-main\venv\lib\site-packages (from pandas->finta) (2023.3)
Requirement already satisfied: six>=1.5 in c:\dev\autotrader-main\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->finta) (1.16.0)

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>autotrader demo   
Loading demo files...
  Done.
Traceback (most recent call last):
  File "C:\dev\autotrader-demo-main\autotrader-demo-main\macd_strategy.py", line 3, in <module>
    from finta import TA
ModuleNotFoundError: No module named 'finta'

(venv) C:\dev\autotrader-demo-main\autotrader-demo-main>

##if you notice i already installed all the necessary tools, libraries e.t.c
anything i can try!?
'autotrader-demo-main\macd_strategy.py' this too doesnt exist

**Comment by owinoalfred** [comment]
whenever you can please consider making a video! i beg! thanks!
